/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const importRemoteImage: typeof import('astro-imagetools/api')['importRemoteImage']
}
