const userAccountRecurringElementQuery = `
  {
    userAccountRecurringElement {
      data {
        id
        attributes {
          locale
          Facebook_icon{
            data{
              attributes{
                url
                provider_metadata
                formats
                alternativeText
              }
            }
          }
          Google_icon{
            data{
              attributes{
                url
                provider_metadata
                formats
                alternativeText
              }
            }
          }
          Twitter_icon{
            data{
              attributes{
                url
                provider_metadata
                formats
                alternativeText
              }
            }
          }
          Empty_order_blob{
            data{
              attributes{
                url
                provider_metadata
                formats
                alternativeText
              }
            }
          }
          Empty_order_button_text
          Empty_order_button_link
          Empty_order_text
          Input_label_first_name
          Input_label_last_name
          Input_label_email
          Input_label_phone
          Input_placeholder_first_name
          Input_placeholder_last_name
          Input_placeholder_email
          Input_placeholder_phone
          Input_placeholder_email_or_phone
          Social_media_divider_or_text
          Input_label_country
          Input_placeholder_country
          Input_label_city
          Input_placeholder_city
          Input_label_street
          Input_placeholder_street
          Input_label_postal_code
          Input_placeholder_postal_code
          Button_add_text
          Button_edit_text
          Button_update_text
          Button_remove_text
          Button_add_new_address_text
          Button_save_text
          Button_cancel_text
          Button_make_default_text
          Button_buy_again_text
          Button_sold_out_text
          Button_view_all_orders_text
          Button_track_package
          Button_track_package_text
          Label_order
          Label_tag_text
          Tag_default_text
          Tag_others_text
          Tag_others_placeholder_text
          Address_tag {
            Title
          }
          Checkbox_set_default_address_text
          Checkbox_set_billing_address_text
          Notification_address_update_text
          Notification_default_address_update_text
          Notification_billing_address_update_text
          text_saved_Addresses
          text_more_address
          text_hide_more_address
          text_content
          text_connected
          text_not_connected
          text_more_products_in_this_order
          text_estimated_delivery
          text_estimated_shipment
          text_delivered
          localizations {
            data {
              attributes {
                locale
                Facebook_icon{
                  data{
                    attributes{
                      url
                      provider_metadata
                      formats
                      alternativeText
                    }
                  }
                }
                Google_icon{
                  data{
                    attributes{
                      url
                      provider_metadata
                      formats
                      alternativeText
                    }
                  }
                }
                Twitter_icon{
                  data{
                    attributes{
                      url
                      provider_metadata
                      formats
                      alternativeText
                    }
                  }
                }
                Empty_order_blob{
                  data{
                    attributes{
                      url
                      provider_metadata
                      formats
                      alternativeText
                    }
                  }
                }
                Empty_order_button_text
                Empty_order_button_link
                Empty_order_text
                Input_label_first_name
                Input_label_last_name
                Input_label_email
                Input_label_phone
                Input_placeholder_first_name
                Input_placeholder_last_name
                Input_placeholder_email
                Input_placeholder_phone
                Input_placeholder_email_or_phone
                Social_media_divider_or_text
                Input_label_country
                Input_placeholder_country
                Input_label_city
                Input_placeholder_city
                Input_label_street
                Input_placeholder_street
                Input_label_postal_code
                Input_placeholder_postal_code
                Button_add_text
                Button_edit_text
                Button_update_text
                Button_remove_text
                Button_add_new_address_text
                Button_save_text
                Button_cancel_text
                Button_make_default_text
                Button_buy_again_text
                Button_sold_out_text
                Button_view_all_orders_text
                Button_track_package
                Button_track_package_text
                Label_order
                Label_tag_text
                Tag_default_text
                Tag_others_text
                Tag_others_placeholder_text
                Address_tag {
                  Title
                }
                Checkbox_set_default_address_text
                Checkbox_set_billing_address_text
                Notification_address_update_text
                Notification_default_address_update_text
                Notification_billing_address_update_text
                text_saved_Addresses
                text_more_address
                text_hide_more_address
                text_content
                text_connected
                text_not_connected
                text_more_products_in_this_order
                text_estimated_delivery
                text_estimated_shipment
                text_delivered
              }
            }
          }
        }
      }
    }
  }
`;

export default userAccountRecurringElementQuery;