name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "\U0001F41B BUG:"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ##  Quick Checklist
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.

        ✅ If you want to report a feature request or improvement contact the product owner.

  - type: input
    id: bug-device
    attributes:
      label: What device are you using?
      placeholder: M2 Macbook Air
    validations:
      required: true
           
  - type: input
    id: bug-os
    attributes:
      label: What operating system are you using?
      placeholder: macOS
    validations:
      required: true
      
  - type: input
    id: bug-browser
    attributes:
      label: What browser are you using and what is its version?
      placeholder: Safari 16
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
      
  - type: textarea
    id: bug-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: bug-additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
