name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "\U0001F41B BUG:"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ##  Quick Checklist
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.
        
        ✅ If you want to report a feature request or improvement contact the product owner.
 - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
 - type: textarea
    id: bug-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
      placeholder: 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
 - type: textarea
    id: bug-expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
 - type: textarea
    id: bug-desktop
    attributes:
      label: Desktop
      description: Please complete the following information for desktop
    validations:
      required: false
      placeholder:  - OS: [e.g. iOS] - Browser [e.g. chrome, safari] - Version [e.g. 22]
 - type: textarea
    id: bug-smartphone
    attributes:
      label: Smartphone
      description: Please complete the following information for smartphone
    validations:
      required: false
      placeholder:   - Device: [e.g. iPhone6] - OS: [e.g. iOS8.1] - Browser [e.g. stock browser, safari] - Version [e.g. 22]
 - type: textarea
    id: bug-additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
