blank_issues_enabled: false
contact_links:
  - name: 💡 Ideas for New Features, Improvements and RFCs
    url: https://jurjendevries.com/
    about: Propose and discuss future improvements to dilmahtea.me with the Product owner. Approved ones will be added to https://wekan.dilmahtea.io/b/kmag7iye5FgJsMmD5/dilmahtea-me-sprint
  - name: 👾 Chat
    url: https://matrix.to/#/!jKdJdcZFefdEvKfrDs:matrix.org?via=matrix.org
    about: Dilmah Matrix space. Invite only.
