name: matrix-action
on: push
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: Numericas/matrix-action@v1.2.1
        with:
          server: ${{ secrets.matrix.org }}
          room-id: ${{ secrets.!wkkpBJHvvVHkDGYJlD:matrix.org }}
          user: ${{ secrets.@teahotbot:matrix.org }}
          password: ${{ secrets.R4Qj4YgkXkPGyndg }}
          status: ${{ job.status }}
